name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,redis]"
        pip install pytest pytest-cov black isort flake8

    - name: Install Redis CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y redis-tools

    - name: Verify Redis connection
      run: |
        redis-cli ping
        echo "Redis is running and accessible"

    - name: Run Black formatter check
      run: python -m black --check --diff mcp-server/

    - name: Run isort import sorting check
      run: python -m isort --check-only --diff mcp-server/

    - name: Run flake8 linter
      run: python -m flake8 mcp-server/

    - name: Run tests
      env:
        STORAGE_CONNECTION_STRING: "redis://localhost:6379/15"
      run: |
        python -m pytest tests/ -v
