name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '*.md'

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install documentation dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Check for broken links in README
      run: |
        # Simple check for basic markdown syntax
        python -c "
        import re
        with open('README.md', 'r') as f:
            content = f.read()
        # Check for broken markdown links
        broken_links = re.findall(r'\[([^\]]+)\]\(([^)]+)\)', content)
        print(f'Found {len(broken_links)} markdown links')
        "

    - name: Validate docs structure
      run: |
        # Check if required documentation files exist
        required_files=(
          "README.md"
        )
        
        for file in "${required_files[@]}"; do
          if [ -f "$file" ]; then
            echo "✅ $file exists"
          else
            echo "❌ $file is missing"
            exit 1
          fi
        done

  spell-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install aspell
      run: sudo apt-get update && sudo apt-get install -y aspell aspell-en

    - name: Run spell check on README
      run: |
        # Basic spell check (can be extended with custom dictionary)
        aspell --mode=markdown --personal=./.aspell.en.pws list < README.md > spelling_errors.txt || true
        if [ -s spelling_errors.txt ]; then
          echo "Potential spelling errors found:"
          cat spelling_errors.txt
          echo "Note: These might be technical terms or false positives"
        else
          echo "No obvious spelling errors found"
        fi
